
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace LightSwitchApplication

    #Region "Data Workspace"
    
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Public NotInheritable Class DataWorkspace
        Inherits Global.Microsoft.LightSwitch.Framework.Base.DataWorkspace(Of Global.LightSwitchApplication.DataWorkspace, Global.LightSwitchApplication.DataWorkspace.DetailsClass)
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Initializes a new instance of a DataWorkspace.  Changes can be made to data sources in the new instance independent of changes made to data sources in the default DataWorkspace.
        ''' </summary>
        Public Sub New()
            MyBase.New()
        End Sub
    
        #End Region
    
        #Region "Public Properties"
    
        ''' <summary>
        ''' Gets the NeuroPatData datasource.  This provides members to query and update data in the data source.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property NeuroPatData As Global.LightSwitchApplication.NeuroPatDataService
            Get
                Return Global.LightSwitchApplication.DataWorkspace.DetailsClass.GetValue(Me, Global.LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.NeuroPatData)
            End Get
        End Property
        
        #End Region
    
        #Region "Details Class"
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.DataWorkspaceDetails(Of Global.LightSwitchApplication.DataWorkspace, Global.LightSwitchApplication.DataWorkspace.DetailsClass, Global.LightSwitchApplication.DataWorkspace.DetailsClass.PropertySet)
    
            Shared Sub New()
                Dim initializeEntry = Global.LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.NeuroPatData
            End Sub
    
            Public Sub New()
                MyBase.New()
            End Sub
    
            Public ReadOnly Shadows Property Properties As Global.LightSwitchApplication.DataWorkspace.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.DataWorkspacePropertySet(Of Global.LightSwitchApplication.DataWorkspace, Global.LightSwitchApplication.DataWorkspace.DetailsClass)
    
                Public Sub New()
                    MyBase.New()
                End Sub
    
                Public ReadOnly Property NeuroPatData As Global.Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty(Of Global.LightSwitchApplication.DataWorkspace, Global.LightSwitchApplication.DataWorkspace.DetailsClass, Global.LightSwitchApplication.NeuroPatDataService)
                    Get
                        Return TryCast(
                            MyBase.GetItem(Global.LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.NeuroPatData),
                            Global.Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty(Of Global.LightSwitchApplication.DataWorkspace, Global.LightSwitchApplication.DataWorkspace.DetailsClass, Global.LightSwitchApplication.NeuroPatDataService))
                    End Get
                End Property
                
            End Class
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend Class PropertySetProperties
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly NeuroPatData As Global.Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty(Of Global.LightSwitchApplication.DataWorkspace, Global.LightSwitchApplication.DataWorkspace.DetailsClass, Global.LightSwitchApplication.NeuroPatDataService).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty(Of Global.LightSwitchApplication.DataWorkspace, Global.LightSwitchApplication.DataWorkspace.DetailsClass, Global.LightSwitchApplication.NeuroPatDataService).Entry( _
                        "NeuroPatData", _
                        AddressOf Global.LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties._NeuroPatData_Stub)
                Private Shared Sub _NeuroPatData_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.DataWorkspace.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty(Of Global.LightSwitchApplication.DataWorkspace, Global.LightSwitchApplication.DataWorkspace.DetailsClass, Global.LightSwitchApplication.NeuroPatDataService).Data), d As Global.LightSwitchApplication.DataWorkspace.DetailsClass, sf As Object)
                    c(d, d._NeuroPatData, sf)
                End Sub
                 
            End Class
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _NeuroPatData As Global.Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty(Of Global.LightSwitchApplication.DataWorkspace, Global.LightSwitchApplication.DataWorkspace.DetailsClass, Global.LightSwitchApplication.NeuroPatDataService).Data
            
        End Class
    
        #End Region
    
    End Class
    
    #End Region
    
    #Region "Data Services"
    
    ''' <summary>
    ''' Provides members to query and update data in the NeuroPatData datasource.
    ''' </summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Public Class NeuroPatData
        Inherits Global.Microsoft.LightSwitch.Framework.Base.DataService(Of Global.LightSwitchApplication.NeuroPatData, Global.LightSwitchApplication.NeuroPatData.DetailsClass)
    
        #Region "Constructors"
    
        ''' <summary>
        ''' This constructor is used for the internal LightSwitch framework. Use DataWorkspace instead.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)>
        Public Sub New()
            MyBase.New()
        End Sub
    
        #End Region
    
        #Region "Public Properties"
    
        ''' <summary>
        ''' Gets the Patient_Mains entity set.  The entity set provides members to access entities of a specific type.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property Patient_Mains As Global.Microsoft.LightSwitch.Framework.EntitySet(Of Global.LightSwitchApplication.Patient_Main)
            Get
                Return Global.LightSwitchApplication.NeuroPatData.DetailsClass.GetValue(Me, Global.LightSwitchApplication.NeuroPatData.DetailsClass.PropertySetProperties.Patient_Mains)
            End Get
        End Property
        
        #End Region
    
        #Region "Queries"
    
        ''' <summary>
        ''' Returns the entity whose identity is specified by the parameter(s).
        ''' </summary>
        ''' <param name="Discharged">
        ''' The value of the 'Discharged' key property of the entity to retrieve.
        ''' </param>
        ''' <param name="Complication">
        ''' The value of the 'Complication' key property of the entity to retrieve.
        ''' </param>
        ''' <param name="M___M">
        ''' The value of the 'M___M' key property of the entity to retrieve.
        ''' </param>
        ''' <param name="TBI">
        ''' The value of the 'TBI' key property of the entity to retrieve.
        ''' </param>
        ''' <param name="TBI_f_u_complete">
        ''' The value of the 'TBI_f_u_complete' key property of the entity to retrieve.
        ''' </param>
        ''' <param name="Preferred_1">
        ''' The value of the 'Preferred_1' key property of the entity to retrieve.
        ''' </param>
        ''' <param name="Preferred_2">
        ''' The value of the 'Preferred_2' key property of the entity to retrieve.
        ''' </param>
        ''' <param name="Preferred_3">
        ''' The value of the 'Preferred_3' key property of the entity to retrieve.
        ''' </param>
        ''' <param name="PCP_f_u_done">
        ''' The value of the 'PCP_f_u_done' key property of the entity to retrieve.
        ''' </param>
        Public Function Patient_Mains_Single(ByVal Discharged As Global.System.Nullable(Of Boolean), ByVal Complication As Global.System.Nullable(Of Boolean), ByVal M___M As Global.System.Nullable(Of Boolean), ByVal TBI As Global.System.Nullable(Of Boolean), ByVal TBI_f_u_complete As Global.System.Nullable(Of Boolean), ByVal Preferred_1 As Global.System.Nullable(Of Boolean), ByVal Preferred_2 As Global.System.Nullable(Of Boolean), ByVal Preferred_3 As Global.System.Nullable(Of Boolean), ByVal PCP_f_u_done As Global.System.Nullable(Of Boolean)) As Global.LightSwitchApplication.Patient_Main
            Return Me.Details.Methods.Patient_Mains_Single.CreateInvocation(Discharged, Complication, M___M, TBI, TBI_f_u_complete, Preferred_1, Preferred_2, Preferred_3, PCP_f_u_done).Execute()
        End Function
        
        ''' <summary>
        ''' Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        ''' </summary>
        ''' <param name="Discharged">
        ''' The value of the 'Discharged' key property of the entity to retrieve.
        ''' </param>
        ''' <param name="Complication">
        ''' The value of the 'Complication' key property of the entity to retrieve.
        ''' </param>
        ''' <param name="M___M">
        ''' The value of the 'M___M' key property of the entity to retrieve.
        ''' </param>
        ''' <param name="TBI">
        ''' The value of the 'TBI' key property of the entity to retrieve.
        ''' </param>
        ''' <param name="TBI_f_u_complete">
        ''' The value of the 'TBI_f_u_complete' key property of the entity to retrieve.
        ''' </param>
        ''' <param name="Preferred_1">
        ''' The value of the 'Preferred_1' key property of the entity to retrieve.
        ''' </param>
        ''' <param name="Preferred_2">
        ''' The value of the 'Preferred_2' key property of the entity to retrieve.
        ''' </param>
        ''' <param name="Preferred_3">
        ''' The value of the 'Preferred_3' key property of the entity to retrieve.
        ''' </param>
        ''' <param name="PCP_f_u_done">
        ''' The value of the 'PCP_f_u_done' key property of the entity to retrieve.
        ''' </param>
        Public Function Patient_Mains_SingleOrDefault(ByVal Discharged As Global.System.Nullable(Of Boolean), ByVal Complication As Global.System.Nullable(Of Boolean), ByVal M___M As Global.System.Nullable(Of Boolean), ByVal TBI As Global.System.Nullable(Of Boolean), ByVal TBI_f_u_complete As Global.System.Nullable(Of Boolean), ByVal Preferred_1 As Global.System.Nullable(Of Boolean), ByVal Preferred_2 As Global.System.Nullable(Of Boolean), ByVal Preferred_3 As Global.System.Nullable(Of Boolean), ByVal PCP_f_u_done As Global.System.Nullable(Of Boolean)) As Global.LightSwitchApplication.Patient_Main
            Return Me.Details.Methods.Patient_Mains_SingleOrDefault.CreateInvocation(Discharged, Complication, M___M, TBI, TBI_f_u_complete, Preferred_1, Preferred_2, Preferred_3, PCP_f_u_done).Execute()
        End Function
        
        #End Region
    
        #Region "Details Class"
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.DataServiceDetails(Of Global.LightSwitchApplication.NeuroPatData, Global.LightSwitchApplication.NeuroPatData.DetailsClass, Global.LightSwitchApplication.NeuroPatData.DetailsClass.PropertySet, Global.LightSwitchApplication.NeuroPatData.DetailsClass.MethodSet)
    
            Shared Sub New()
                Dim initializeMethodEntry = Global.LightSwitchApplication.NeuroPatData.DetailsClass.MethodSetProperties.Patient_Mains_Single
                Dim initializePropertyEntry = Global.LightSwitchApplication.NeuroPatData.DetailsClass.PropertySetProperties.Patient_Mains
            End Sub
    
            Public Sub New()
                MyBase.New()
            End Sub
    
            Public ReadOnly Shadows Property Methods As Global.LightSwitchApplication.NeuroPatData.DetailsClass.MethodSet
                Get
                    Return MyBase.Methods
                End Get
            End Property
    
            Public ReadOnly Shadows Property Properties As Global.LightSwitchApplication.NeuroPatData.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class MethodSet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.DataServiceMethodSet(Of Global.LightSwitchApplication.NeuroPatData, Global.LightSwitchApplication.NeuroPatData.DetailsClass)
    
                Public Sub New()
                    MyBase.New()
                End Sub
    
                Public ReadOnly Property Patient_Mains_Single As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.NeuroPatData, Global.LightSwitchApplication.NeuroPatData.DetailsClass, Global.LightSwitchApplication.Patient_Main)
                    Get
                        Return TryCast(
                            MyBase.GetItem(Global.LightSwitchApplication.NeuroPatData.DetailsClass.MethodSetProperties.Patient_Mains_Single),
                            Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.NeuroPatData, Global.LightSwitchApplication.NeuroPatData.DetailsClass, Global.LightSwitchApplication.Patient_Main))
                    End Get
                End Property
                
                Public ReadOnly Property Patient_Mains_SingleOrDefault As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.NeuroPatData, Global.LightSwitchApplication.NeuroPatData.DetailsClass, Global.LightSwitchApplication.Patient_Main)
                    Get
                        Return TryCast(
                            MyBase.GetItem(Global.LightSwitchApplication.NeuroPatData.DetailsClass.MethodSetProperties.Patient_Mains_SingleOrDefault),
                            Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.NeuroPatData, Global.LightSwitchApplication.NeuroPatData.DetailsClass, Global.LightSwitchApplication.Patient_Main))
                    End Get
                End Property
                
            End Class
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.DataServicePropertySet(Of Global.LightSwitchApplication.NeuroPatData, Global.LightSwitchApplication.NeuroPatData.DetailsClass)
    
                Public Sub New()
                    MyBase.New()
                End Sub
    
                Public ReadOnly Property Patient_Mains As Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.NeuroPatData, Global.LightSwitchApplication.NeuroPatData.DetailsClass, Global.LightSwitchApplication.Patient_Main)
                    Get
                        Return TryCast(
                            MyBase.GetItem(Global.LightSwitchApplication.NeuroPatData.DetailsClass.PropertySetProperties.Patient_Mains),
                            Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.NeuroPatData, Global.LightSwitchApplication.NeuroPatData.DetailsClass, Global.LightSwitchApplication.Patient_Main))
                    End Get
                End Property
                
            End Class
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend Class MethodSetProperties
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Patient_Mains_Single As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.NeuroPatData, Global.LightSwitchApplication.NeuroPatData.DetailsClass, Global.LightSwitchApplication.Patient_Main).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.NeuroPatData, Global.LightSwitchApplication.NeuroPatData.DetailsClass, Global.LightSwitchApplication.Patient_Main).Entry( _
                        "Patient_Mains_Single", _
                        AddressOf Global.LightSwitchApplication.NeuroPatData.DetailsClass.MethodSetProperties._Patient_Mains_Single_Stub)
                Private Shared Sub _Patient_Mains_Single_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.NeuroPatData.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.NeuroPatData, Global.LightSwitchApplication.NeuroPatData.DetailsClass, Global.LightSwitchApplication.Patient_Main).Data), d As Global.LightSwitchApplication.NeuroPatData.DetailsClass, sf As Object)
                    c(d, d._Patient_Mains_Single, sf)
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Patient_Mains_SingleOrDefault As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.NeuroPatData, Global.LightSwitchApplication.NeuroPatData.DetailsClass, Global.LightSwitchApplication.Patient_Main).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.NeuroPatData, Global.LightSwitchApplication.NeuroPatData.DetailsClass, Global.LightSwitchApplication.Patient_Main).Entry( _
                        "Patient_Mains_SingleOrDefault", _
                        AddressOf Global.LightSwitchApplication.NeuroPatData.DetailsClass.MethodSetProperties._Patient_Mains_SingleOrDefault_Stub)
                Private Shared Sub _Patient_Mains_SingleOrDefault_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.NeuroPatData.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.NeuroPatData, Global.LightSwitchApplication.NeuroPatData.DetailsClass, Global.LightSwitchApplication.Patient_Main).Data), d As Global.LightSwitchApplication.NeuroPatData.DetailsClass, sf As Object)
                    c(d, d._Patient_Mains_SingleOrDefault, sf)
                End Sub
    
            End Class
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend Class PropertySetProperties
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Patient_Mains As Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.NeuroPatData, Global.LightSwitchApplication.NeuroPatData.DetailsClass, Global.LightSwitchApplication.Patient_Main).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.NeuroPatData, Global.LightSwitchApplication.NeuroPatData.DetailsClass, Global.LightSwitchApplication.Patient_Main).Entry( _
                        "Patient_Mains", _
                        AddressOf Global.LightSwitchApplication.NeuroPatData.DetailsClass.PropertySetProperties._Patient_Mains_Stub)
                Private Shared Sub _Patient_Mains_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.NeuroPatData.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.NeuroPatData, Global.LightSwitchApplication.NeuroPatData.DetailsClass, Global.LightSwitchApplication.Patient_Main).Data), d As Global.LightSwitchApplication.NeuroPatData.DetailsClass, sf As Object)
                    c(d, d._Patient_Mains, sf)
                End Sub
     
            End Class
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Patient_Mains As Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.NeuroPatData, Global.LightSwitchApplication.NeuroPatData.DetailsClass, Global.LightSwitchApplication.Patient_Main).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Patient_Mains_Single As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.NeuroPatData, Global.LightSwitchApplication.NeuroPatData.DetailsClass, Global.LightSwitchApplication.Patient_Main).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Patient_Mains_SingleOrDefault As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.NeuroPatData, Global.LightSwitchApplication.NeuroPatData.DetailsClass, Global.LightSwitchApplication.Patient_Main).Data
            
        End Class
    
        #End Region
    
    End Class
    
    #End Region
    
End Namespace
