'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace LightSwitchApplication

    #Region "Data Services"
    
    ''' <summary>
    ''' Provides members to query and update data in the NeuroPatData datasource.
    ''' </summary>
    Public NotInheritable Partial Class NeuroPatDataService
        Inherits Global.LightSwitchApplication.NeuroPatData
    
        #Region "Constructors"
    
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New()
            MyBase.New()
        End Sub
    
        #End Region
    
        #Region "Private Properties"
        
        ''' <summary>
        ''' Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property Application As Global.LightSwitchApplication.Application
            Get
                Return Global.LightSwitchApplication.Application.Current
            End Get
        End Property
        
        ''' <summary>
        ''' Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property DataWorkspace As Global.LightSwitchApplication.DataWorkspace
            Get
                Return DirectCast(Me.Details.DataWorkspace, Global.LightSwitchApplication.DataWorkspace)
            End Get
        End Property
        
        #End Region
    
        #Region "Server Interceptions Points"
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Patient_Mains_CanRead(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Patient_Mains_Validate(ByVal entity As Global.LightSwitchApplication.Patient_Main, ByVal results As Global.Microsoft.LightSwitch.EntitySetValidationResultsBuilder)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Patient_Mains_Filter(ByRef filter As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.Patient_Main, Boolean)))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub SaveChanges_CanExecute(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub SaveChanges_Executing()
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub SaveChanges_Executed()
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub SaveChanges_ExecuteFailed(ByVal exception As Global.System.Exception)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Query_Executing(ByVal queryDescriptor As Global.Microsoft.LightSwitch.QueryExecutingDescriptor)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Query_Executed(ByVal queryDescriptor As Global.Microsoft.LightSwitch.QueryExecutedDescriptor)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Query_ExecuteFailed(ByVal queryDescriptor As Global.Microsoft.LightSwitch.QueryExecuteFailedDescriptor)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub NeuroPatData_InitializingConnection(ByVal state As Global.Microsoft.LightSwitch.DatabaseConnectionState)
        End Sub
    
        #End Region
        
        #Region "Details Class"
    
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
        Public MustInherit Shadows Class DetailsClass
    
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline")> _
            Shared Sub New()
            End Sub
    
            Private Sub New()
            End Sub
            
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")> _
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            Private Shared ReadOnly __Patient_MainsEntry As Global.Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry(Of Global.LightSwitchApplication.NeuroPatDataService, Global.LightSwitchApplication.Patient_Main) = _
                New Global.Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry(Of Global.LightSwitchApplication.NeuroPatDataService, Global.LightSwitchApplication.Patient_Main)( _
                    "Patient_Mains",
                    Nothing, _
                    Nothing, _
                    Nothing, _
                    AddressOf Global.LightSwitchApplication.NeuroPatDataService.DetailsClass.__Patient_Mains_CanRead, _
                    Nothing, _
                    Nothing, _
                    Nothing, _
                    Nothing, _
                    Nothing, _
                    Nothing, _
                    AddressOf Global.LightSwitchApplication.NeuroPatDataService.DetailsClass.__Patient_Mains_Validate, _
                    AddressOf Global.LightSwitchApplication.NeuroPatDataService.DetailsClass.__Patient_Mains_Filter)
            Private Shared Function __Patient_Mains_CanRead(d As Global.LightSwitchApplication.NeuroPatDataService) As Boolean
                Dim result As Boolean = True
                d.Patient_Mains_CanRead(result)
                Return result
            End Function
            Private Shared Sub __Patient_Mains_Validate(d As Global.LightSwitchApplication.NeuroPatDataService, e As Global.LightSwitchApplication.Patient_Main, r As Global.Microsoft.LightSwitch.EntitySetValidationResultsBuilder)
                d.Patient_Mains_Validate(e, r)
            End Sub
            Private Shared Function __Patient_Mains_Filter(d As Global.LightSwitchApplication.NeuroPatDataService) As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.Patient_Main, Boolean))
                Dim filter As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.Patient_Main, Boolean)) = Nothing
                d.Patient_Mains_Filter(filter)
                return filter
            End Function
            
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")> _
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            Private Shared ReadOnly __SaveChangesEntry As Global.Microsoft.LightSwitch.Details.Framework.Server.OperationEntry(Of Global.LightSwitchApplication.NeuroPatDataService) = _
                New Global.Microsoft.LightSwitch.Details.Framework.Server.OperationEntry(Of Global.LightSwitchApplication.NeuroPatDataService)( _
                    "SaveChanges",
                    AddressOf Global.LightSwitchApplication.NeuroPatDataService.DetailsClass.__SaveChanges_CanExecute, _
                    AddressOf Global.LightSwitchApplication.NeuroPatDataService.DetailsClass.__SaveChanges_Executing, _
                    AddressOf Global.LightSwitchApplication.NeuroPatDataService.DetailsClass.__SaveChanges_Executed, _
                    AddressOf Global.LightSwitchApplication.NeuroPatDataService.DetailsClass.__SaveChanges_Failed)
            Private Shared Function __SaveChanges_CanExecute(d As Global.LightSwitchApplication.NeuroPatDataService, r As Boolean) As Boolean
                d.SaveChanges_CanExecute(r)
                Return r
            End Function
            Private Shared Sub __SaveChanges_Executing(d As Global.LightSwitchApplication.NeuroPatDataService, args As Object())
                d.SaveChanges_Executing()
            End Sub
            Private Shared Sub __SaveChanges_Executed(d As Global.LightSwitchApplication.NeuroPatDataService, args As Object())
                d.SaveChanges_Executed()
            End Sub
            Private Shared Sub __SaveChanges_Failed(d As Global.LightSwitchApplication.NeuroPatDataService, args As Object(), ex As Global.System.Exception)
                d.SaveChanges_ExecuteFailed(ex)
            End Sub
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")> _
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        Private Shared ReadOnly ___QueryEntry As Global.Microsoft.LightSwitch.Details.Framework.Server.QueryEntry(Of Global.LightSwitchApplication.NeuroPatDataService) = _
            New Global.Microsoft.LightSwitch.Details.Framework.Server.QueryEntry(Of Global.LightSwitchApplication.NeuroPatDataService)( _
                AddressOf Global.LightSwitchApplication.NeuroPatDataService.DetailsClass.__Query_Executing, _
                AddressOf Global.LightSwitchApplication.NeuroPatDataService.DetailsClass.__Query_Executed, _
                AddressOf Global.LightSwitchApplication.NeuroPatDataService.DetailsClass.__Query_Failed)
        Private Shared Sub __Query_Executing(d As Global.LightSwitchApplication.NeuroPatDataService, queryDescriptor As Global.Microsoft.LightSwitch.QueryExecutingDescriptor)
            d.Query_Executing(queryDescriptor)
        End Sub
        Private Shared Sub __Query_Executed(d As Global.LightSwitchApplication.NeuroPatDataService, queryDescriptor As Global.Microsoft.LightSwitch.QueryExecutedDescriptor)
            d.Query_Executed(queryDescriptor)
        End Sub
        Private Shared Sub __Query_Failed(d As Global.LightSwitchApplication.NeuroPatDataService, queryDescriptor As Global.Microsoft.LightSwitch.QueryExecuteFailedDescriptor)
            d.Query_ExecuteFailed(queryDescriptor)
        End Sub
    
    
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")> _
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        Private Shared ReadOnly ___DatabaseAuthEntry As Global.Microsoft.LightSwitch.Details.Framework.Server.DatabaseAuthEntry(Of Global.LightSwitchApplication.NeuroPatDataService) = _
            New Global.Microsoft.LightSwitch.Details.Framework.Server.DatabaseAuthEntry(Of Global.LightSwitchApplication.NeuroPatDataService)( _
                AddressOf Global.LightSwitchApplication.NeuroPatDataService.DetailsClass.__NeuroPatData_InitializingConnection)
        Private Shared Sub __NeuroPatData_InitializingConnection(d As Global.LightSwitchApplication.NeuroPatDataService, state As Global.Microsoft.LightSwitch.DatabaseConnectionState)
            d.NeuroPatData_InitializingConnection(state)
        End Sub
        End Class
    
        #End Region
    
    End Class
    
    #End Region

End Namespace
