
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("c4201584-670d-48cc-9af6-f40351baf3d4")>
Namespace LightSwitchApplication.Implementation

    #Region "Contexts"
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public Partial Class NeuroPatData
        Inherits ObjectContext
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Initializes a new NeuroPatData object using the connection string found in the 'NeuroPatData' section of the application configuration file.
        ''' </summary>
        Public Sub New()
            MyBase.New("name=NeuroPatData", "NeuroPatData")
            OnContextCreated()
        End Sub
    
        ''' <summary>
        ''' Initialize a new NeuroPatData object.
        ''' </summary>
        Public Sub New(ByVal connectionString As String)
            MyBase.New(connectionString, "NeuroPatData")
            OnContextCreated()
        End Sub
    
        ''' <summary>
        ''' Initialize a new NeuroPatData object.
        ''' </summary>
        Public Sub New(ByVal connection As EntityConnection)
            MyBase.New(connection, "NeuroPatData")
            OnContextCreated()
        End Sub
    
        #End Region
    
        #Region "Partial Methods"
    
        Partial Private Sub OnContextCreated()
        End Sub
    
        #End Region
    
        #Region "ObjectSet Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property Patient_Mains() As ObjectSet(Of Patient_Main)
            Get
                If (_Patient_Mains Is Nothing) Then
                    _Patient_Mains = MyBase.CreateObjectSet(Of Patient_Main)("Patient_Mains")
                End If
                Return _Patient_Mains
            End Get
        End Property
    
        Private _Patient_Mains As ObjectSet(Of Patient_Main)

        #End Region

        #Region "AddTo Methods"
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the Patient_Mains EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToPatient_Mains(ByVal patient_Main As Patient_Main)
            MyBase.AddObject("Patient_Mains", patient_Main)
        End Sub

        #End Region

    End Class

    #End Region

    #Region "Entities"
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="LightSwitchApplication", Name:="Patient_Main")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class Patient_Main
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new Patient_Main object.
        ''' </summary>
        ''' <param name="discharged">Initial value of the Discharged property.</param>
        ''' <param name="complication">Initial value of the Complication property.</param>
        ''' <param name="m___M">Initial value of the M___M property.</param>
        ''' <param name="tBI">Initial value of the TBI property.</param>
        ''' <param name="tBI_f_u_complete">Initial value of the TBI_f_u_complete property.</param>
        ''' <param name="preferred_1">Initial value of the Preferred_1 property.</param>
        ''' <param name="preferred_2">Initial value of the Preferred_2 property.</param>
        ''' <param name="preferred_3">Initial value of the Preferred_3 property.</param>
        ''' <param name="pCP_f_u_done">Initial value of the PCP_f_u_done property.</param>
        Public Shared Function CreatePatient_Main(discharged As Global.System.Boolean, complication As Global.System.Boolean, m___M As Global.System.Boolean, tBI As Global.System.Boolean, tBI_f_u_complete As Global.System.Boolean, preferred_1 As Global.System.Boolean, preferred_2 As Global.System.Boolean, preferred_3 As Global.System.Boolean, pCP_f_u_done As Global.System.Boolean) As Patient_Main
            Dim patient_Main as Patient_Main = New Patient_Main
            patient_Main.Discharged = discharged
            patient_Main.Complication = complication
            patient_Main.M___M = m___M
            patient_Main.TBI = tBI
            patient_Main.TBI_f_u_complete = tBI_f_u_complete
            patient_Main.Preferred_1 = preferred_1
            patient_Main.Preferred_2 = preferred_2
            patient_Main.Preferred_3 = preferred_3
            patient_Main.PCP_f_u_done = pCP_f_u_done
            Return patient_Main
        End Function

        #End Region

        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property ID1() As Nullable(Of Global.System.Int32)
            Get
                Return _ID1
            End Get
            Set
                OnID1Changing(value)
                ReportPropertyChanging("ID1")
                _ID1 = value
                ReportPropertyChanged("ID1")
                OnID1Changed()
            End Set
        End Property
    
        Private _ID1 As Nullable(Of Global.System.Int32)
        Private Partial Sub OnID1Changing(value As Nullable(Of Global.System.Int32))
        End Sub
    
        Private Partial Sub OnID1Changed()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Last_Name() As Global.System.String
            Get
                Return _Last_Name
            End Get
            Set
                OnLast_NameChanging(value)
                ReportPropertyChanging("Last_Name")
                _Last_Name = value
                ReportPropertyChanged("Last_Name")
                OnLast_NameChanged()
            End Set
        End Property
    
        Private _Last_Name As Global.System.String
        Private Partial Sub OnLast_NameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnLast_NameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property First_Name() As Global.System.String
            Get
                Return _First_Name
            End Get
            Set
                OnFirst_NameChanging(value)
                ReportPropertyChanging("First_Name")
                _First_Name = value
                ReportPropertyChanged("First_Name")
                OnFirst_NameChanged()
            End Set
        End Property
    
        Private _First_Name As Global.System.String
        Private Partial Sub OnFirst_NameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnFirst_NameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property MR() As Global.System.String
            Get
                Return _MR
            End Get
            Set
                OnMRChanging(value)
                ReportPropertyChanging("MR")
                _MR = value
                ReportPropertyChanged("MR")
                OnMRChanged()
            End Set
        End Property
    
        Private _MR As Global.System.String
        Private Partial Sub OnMRChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnMRChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Age() As Global.System.String
            Get
                Return _Age
            End Get
            Set
                OnAgeChanging(value)
                ReportPropertyChanging("Age")
                _Age = value
                ReportPropertyChanged("Age")
                OnAgeChanged()
            End Set
        End Property
    
        Private _Age As Global.System.String
        Private Partial Sub OnAgeChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnAgeChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Admit_Date() As Nullable(Of Global.System.DateTime)
            Get
                Return _Admit_Date
            End Get
            Set
                OnAdmit_DateChanging(value)
                ReportPropertyChanging("Admit_Date")
                _Admit_Date = value
                ReportPropertyChanged("Admit_Date")
                OnAdmit_DateChanged()
            End Set
        End Property
    
        Private _Admit_Date As Nullable(Of Global.System.DateTime)
        Private Partial Sub OnAdmit_DateChanging(value As Nullable(Of Global.System.DateTime))
        End Sub
    
        Private Partial Sub OnAdmit_DateChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Floor() As Global.System.String
            Get
                Return _Floor
            End Get
            Set
                OnFloorChanging(value)
                ReportPropertyChanging("Floor")
                _Floor = value
                ReportPropertyChanged("Floor")
                OnFloorChanged()
            End Set
        End Property
    
        Private _Floor As Global.System.String
        Private Partial Sub OnFloorChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnFloorChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Bed() As Nullable(Of Global.System.Int32)
            Get
                Return _Bed
            End Get
            Set
                OnBedChanging(value)
                ReportPropertyChanging("Bed")
                _Bed = value
                ReportPropertyChanged("Bed")
                OnBedChanged()
            End Set
        End Property
    
        Private _Bed As Nullable(Of Global.System.Int32)
        Private Partial Sub OnBedChanging(value As Nullable(Of Global.System.Int32))
        End Sub
    
        Private Partial Sub OnBedChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Staff() As Global.System.String
            Get
                Return _Staff
            End Get
            Set
                OnStaffChanging(value)
                ReportPropertyChanging("Staff")
                _Staff = value
                ReportPropertyChanged("Staff")
                OnStaffChanged()
            End Set
        End Property
    
        Private _Staff As Global.System.String
        Private Partial Sub OnStaffChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnStaffChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Op_Res() As Global.System.String
            Get
                Return _Op_Res
            End Get
            Set
                OnOp_ResChanging(value)
                ReportPropertyChanging("Op_Res")
                _Op_Res = value
                ReportPropertyChanged("Op_Res")
                OnOp_ResChanged()
            End Set
        End Property
    
        Private _Op_Res As Global.System.String
        Private Partial Sub OnOp_ResChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnOp_ResChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Op_Res_2() As Global.System.String
            Get
                Return _Op_Res_2
            End Get
            Set
                OnOp_Res_2Changing(value)
                ReportPropertyChanging("Op_Res_2")
                _Op_Res_2 = value
                ReportPropertyChanged("Op_Res_2")
                OnOp_Res_2Changed()
            End Set
        End Property
    
        Private _Op_Res_2 As Global.System.String
        Private Partial Sub OnOp_Res_2Changing(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnOp_Res_2Changed()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Consult_Inpatient() As Global.System.String
            Get
                Return _Consult_Inpatient
            End Get
            Set
                OnConsult_InpatientChanging(value)
                ReportPropertyChanging("Consult_Inpatient")
                _Consult_Inpatient = value
                ReportPropertyChanged("Consult_Inpatient")
                OnConsult_InpatientChanged()
            End Set
        End Property
    
        Private _Consult_Inpatient As Global.System.String
        Private Partial Sub OnConsult_InpatientChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnConsult_InpatientChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Diagnosis() As Global.System.String
            Get
                Return _Diagnosis
            End Get
            Set
                OnDiagnosisChanging(value)
                ReportPropertyChanging("Diagnosis")
                _Diagnosis = value
                ReportPropertyChanged("Diagnosis")
                OnDiagnosisChanged()
            End Set
        End Property
    
        Private _Diagnosis As Global.System.String
        Private Partial Sub OnDiagnosisChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnDiagnosisChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Procedures() As Global.System.String
            Get
                Return _Procedures
            End Get
            Set
                OnProceduresChanging(value)
                ReportPropertyChanging("Procedures")
                _Procedures = value
                ReportPropertyChanged("Procedures")
                OnProceduresChanged()
            End Set
        End Property
    
        Private _Procedures As Global.System.String
        Private Partial Sub OnProceduresChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnProceduresChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Note() As Global.System.String
            Get
                Return _Note
            End Get
            Set
                OnNoteChanging(value)
                ReportPropertyChanging("Note")
                _Note = value
                ReportPropertyChanged("Note")
                OnNoteChanged()
            End Set
        End Property
    
        Private _Note As Global.System.String
        Private Partial Sub OnNoteChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnNoteChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Discharged() As Global.System.Boolean
            Get
                Return _Discharged
            End Get
            Set
                If (_Discharged <> Value) Then
                    OnDischargedChanging(value)
                    ReportPropertyChanging("Discharged")
                    _Discharged = value
                    ReportPropertyChanged("Discharged")
                    OnDischargedChanged()
                End If
            End Set
        End Property
    
        Private _Discharged As Global.System.Boolean
        Private Partial Sub OnDischargedChanging(value As Global.System.Boolean)
        End Sub
    
        Private Partial Sub OnDischargedChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Discharge_Date() As Nullable(Of Global.System.DateTime)
            Get
                Return _Discharge_Date
            End Get
            Set
                OnDischarge_DateChanging(value)
                ReportPropertyChanging("Discharge_Date")
                _Discharge_Date = value
                ReportPropertyChanged("Discharge_Date")
                OnDischarge_DateChanged()
            End Set
        End Property
    
        Private _Discharge_Date As Nullable(Of Global.System.DateTime)
        Private Partial Sub OnDischarge_DateChanging(value As Nullable(Of Global.System.DateTime))
        End Sub
    
        Private Partial Sub OnDischarge_DateChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Complication() As Global.System.Boolean
            Get
                Return _Complication
            End Get
            Set
                If (_Complication <> Value) Then
                    OnComplicationChanging(value)
                    ReportPropertyChanging("Complication")
                    _Complication = value
                    ReportPropertyChanged("Complication")
                    OnComplicationChanged()
                End If
            End Set
        End Property
    
        Private _Complication As Global.System.Boolean
        Private Partial Sub OnComplicationChanging(value As Global.System.Boolean)
        End Sub
    
        Private Partial Sub OnComplicationChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Complication__1() As Global.System.String
            Get
                Return _Complication__1
            End Get
            Set
                OnComplication__1Changing(value)
                ReportPropertyChanging("Complication__1")
                _Complication__1 = value
                ReportPropertyChanged("Complication__1")
                OnComplication__1Changed()
            End Set
        End Property
    
        Private _Complication__1 As Global.System.String
        Private Partial Sub OnComplication__1Changing(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnComplication__1Changed()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Complication__2() As Global.System.String
            Get
                Return _Complication__2
            End Get
            Set
                OnComplication__2Changing(value)
                ReportPropertyChanging("Complication__2")
                _Complication__2 = value
                ReportPropertyChanged("Complication__2")
                OnComplication__2Changed()
            End Set
        End Property
    
        Private _Complication__2 As Global.System.String
        Private Partial Sub OnComplication__2Changing(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnComplication__2Changed()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Complication_Description() As Global.System.String
            Get
                Return _Complication_Description
            End Get
            Set
                OnComplication_DescriptionChanging(value)
                ReportPropertyChanging("Complication_Description")
                _Complication_Description = value
                ReportPropertyChanged("Complication_Description")
                OnComplication_DescriptionChanged()
            End Set
        End Property
    
        Private _Complication_Description As Global.System.String
        Private Partial Sub OnComplication_DescriptionChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnComplication_DescriptionChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Research_Pt() As Global.System.String
            Get
                Return _Research_Pt
            End Get
            Set
                OnResearch_PtChanging(value)
                ReportPropertyChanging("Research_Pt")
                _Research_Pt = value
                ReportPropertyChanged("Research_Pt")
                OnResearch_PtChanged()
            End Set
        End Property
    
        Private _Research_Pt As Global.System.String
        Private Partial Sub OnResearch_PtChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnResearch_PtChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property M___M() As Global.System.Boolean
            Get
                Return _M___M
            End Get
            Set
                If (_M___M <> Value) Then
                    OnM___MChanging(value)
                    ReportPropertyChanging("M___M")
                    _M___M = value
                    ReportPropertyChanged("M___M")
                    OnM___MChanged()
                End If
            End Set
        End Property
    
        Private _M___M As Global.System.Boolean
        Private Partial Sub OnM___MChanging(value As Global.System.Boolean)
        End Sub
    
        Private Partial Sub OnM___MChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Status() As Global.System.String
            Get
                Return _Status
            End Get
            Set
                OnStatusChanging(value)
                ReportPropertyChanging("Status")
                _Status = value
                ReportPropertyChanged("Status")
                OnStatusChanged()
            End Set
        End Property
    
        Private _Status As Global.System.String
        Private Partial Sub OnStatusChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnStatusChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property FT() As Nullable(Of Global.System.Int32)
            Get
                Return _FT
            End Get
            Set
                OnFTChanging(value)
                ReportPropertyChanging("FT")
                _FT = value
                ReportPropertyChanged("FT")
                OnFTChanged()
            End Set
        End Property
    
        Private _FT As Nullable(Of Global.System.Int32)
        Private Partial Sub OnFTChanging(value As Nullable(Of Global.System.Int32))
        End Sub
    
        Private Partial Sub OnFTChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property TBI() As Global.System.Boolean
            Get
                Return _TBI
            End Get
            Set
                If (_TBI <> Value) Then
                    OnTBIChanging(value)
                    ReportPropertyChanging("TBI")
                    _TBI = value
                    ReportPropertyChanged("TBI")
                    OnTBIChanged()
                End If
            End Set
        End Property
    
        Private _TBI As Global.System.Boolean
        Private Partial Sub OnTBIChanging(value As Global.System.Boolean)
        End Sub
    
        Private Partial Sub OnTBIChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property TBI_f_u_complete() As Global.System.Boolean
            Get
                Return _TBI_f_u_complete
            End Get
            Set
                If (_TBI_f_u_complete <> Value) Then
                    OnTBI_f_u_completeChanging(value)
                    ReportPropertyChanging("TBI_f_u_complete")
                    _TBI_f_u_complete = value
                    ReportPropertyChanged("TBI_f_u_complete")
                    OnTBI_f_u_completeChanged()
                End If
            End Set
        End Property
    
        Private _TBI_f_u_complete As Global.System.Boolean
        Private Partial Sub OnTBI_f_u_completeChanging(value As Global.System.Boolean)
        End Sub
    
        Private Partial Sub OnTBI_f_u_completeChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property PCP() As Global.System.String
            Get
                Return _PCP
            End Get
            Set
                OnPCPChanging(value)
                ReportPropertyChanging("PCP")
                _PCP = value
                ReportPropertyChanged("PCP")
                OnPCPChanged()
            End Set
        End Property
    
        Private _PCP As Global.System.String
        Private Partial Sub OnPCPChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnPCPChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Address_line__1() As Global.System.String
            Get
                Return _Address_line__1
            End Get
            Set
                OnAddress_line__1Changing(value)
                ReportPropertyChanging("Address_line__1")
                _Address_line__1 = value
                ReportPropertyChanged("Address_line__1")
                OnAddress_line__1Changed()
            End Set
        End Property
    
        Private _Address_line__1 As Global.System.String
        Private Partial Sub OnAddress_line__1Changing(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnAddress_line__1Changed()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Address_line__2() As Global.System.String
            Get
                Return _Address_line__2
            End Get
            Set
                OnAddress_line__2Changing(value)
                ReportPropertyChanging("Address_line__2")
                _Address_line__2 = value
                ReportPropertyChanged("Address_line__2")
                OnAddress_line__2Changed()
            End Set
        End Property
    
        Private _Address_line__2 As Global.System.String
        Private Partial Sub OnAddress_line__2Changing(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnAddress_line__2Changed()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Address_line__3() As Global.System.String
            Get
                Return _Address_line__3
            End Get
            Set
                OnAddress_line__3Changing(value)
                ReportPropertyChanging("Address_line__3")
                _Address_line__3 = value
                ReportPropertyChanged("Address_line__3")
                OnAddress_line__3Changed()
            End Set
        End Property
    
        Private _Address_line__3 As Global.System.String
        Private Partial Sub OnAddress_line__3Changing(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnAddress_line__3Changed()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Preferred_1() As Global.System.Boolean
            Get
                Return _Preferred_1
            End Get
            Set
                If (_Preferred_1 <> Value) Then
                    OnPreferred_1Changing(value)
                    ReportPropertyChanging("Preferred_1")
                    _Preferred_1 = value
                    ReportPropertyChanged("Preferred_1")
                    OnPreferred_1Changed()
                End If
            End Set
        End Property
    
        Private _Preferred_1 As Global.System.Boolean
        Private Partial Sub OnPreferred_1Changing(value As Global.System.Boolean)
        End Sub
    
        Private Partial Sub OnPreferred_1Changed()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property E_mail() As Global.System.String
            Get
                Return _E_mail
            End Get
            Set
                OnE_mailChanging(value)
                ReportPropertyChanging("E_mail")
                _E_mail = value
                ReportPropertyChanged("E_mail")
                OnE_mailChanged()
            End Set
        End Property
    
        Private _E_mail As Global.System.String
        Private Partial Sub OnE_mailChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnE_mailChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Preferred_2() As Global.System.Boolean
            Get
                Return _Preferred_2
            End Get
            Set
                If (_Preferred_2 <> Value) Then
                    OnPreferred_2Changing(value)
                    ReportPropertyChanging("Preferred_2")
                    _Preferred_2 = value
                    ReportPropertyChanged("Preferred_2")
                    OnPreferred_2Changed()
                End If
            End Set
        End Property
    
        Private _Preferred_2 As Global.System.Boolean
        Private Partial Sub OnPreferred_2Changing(value As Global.System.Boolean)
        End Sub
    
        Private Partial Sub OnPreferred_2Changed()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Tel() As Global.System.String
            Get
                Return _Tel
            End Get
            Set
                OnTelChanging(value)
                ReportPropertyChanging("Tel")
                _Tel = value
                ReportPropertyChanged("Tel")
                OnTelChanged()
            End Set
        End Property
    
        Private _Tel As Global.System.String
        Private Partial Sub OnTelChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnTelChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Preferred_3() As Global.System.Boolean
            Get
                Return _Preferred_3
            End Get
            Set
                If (_Preferred_3 <> Value) Then
                    OnPreferred_3Changing(value)
                    ReportPropertyChanging("Preferred_3")
                    _Preferred_3 = value
                    ReportPropertyChanged("Preferred_3")
                    OnPreferred_3Changed()
                End If
            End Set
        End Property
    
        Private _Preferred_3 As Global.System.Boolean
        Private Partial Sub OnPreferred_3Changing(value As Global.System.Boolean)
        End Sub
    
        Private Partial Sub OnPreferred_3Changed()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Referring_Phys() As Global.System.String
            Get
                Return _Referring_Phys
            End Get
            Set
                OnReferring_PhysChanging(value)
                ReportPropertyChanging("Referring_Phys")
                _Referring_Phys = value
                ReportPropertyChanged("Referring_Phys")
                OnReferring_PhysChanged()
            End Set
        End Property
    
        Private _Referring_Phys As Global.System.String
        Private Partial Sub OnReferring_PhysChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnReferring_PhysChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property BC_notes() As Global.System.String
            Get
                Return _BC_notes
            End Get
            Set
                OnBC_notesChanging(value)
                ReportPropertyChanging("BC_notes")
                _BC_notes = value
                ReportPropertyChanged("BC_notes")
                OnBC_notesChanged()
            End Set
        End Property
    
        Private _BC_notes As Global.System.String
        Private Partial Sub OnBC_notesChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnBC_notesChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property KJB_notes() As Global.System.String
            Get
                Return _KJB_notes
            End Get
            Set
                OnKJB_notesChanging(value)
                ReportPropertyChanging("KJB_notes")
                _KJB_notes = value
                ReportPropertyChanged("KJB_notes")
                OnKJB_notesChanged()
            End Set
        End Property
    
        Private _KJB_notes As Global.System.String
        Private Partial Sub OnKJB_notesChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnKJB_notesChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property PCP_f_u_done() As Global.System.Boolean
            Get
                Return _PCP_f_u_done
            End Get
            Set
                If (_PCP_f_u_done <> Value) Then
                    OnPCP_f_u_doneChanging(value)
                    ReportPropertyChanging("PCP_f_u_done")
                    _PCP_f_u_done = value
                    ReportPropertyChanged("PCP_f_u_done")
                    OnPCP_f_u_doneChanged()
                End If
            End Set
        End Property
    
        Private _PCP_f_u_done As Global.System.Boolean
        Private Partial Sub OnPCP_f_u_doneChanging(value As Global.System.Boolean)
        End Sub
    
        Private Partial Sub OnPCP_f_u_doneChanged()
        End Sub

        #End Region

    End Class

    #End Region

    
End Namespace
