
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Data Workspace
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public sealed class DataWorkspace : global::Microsoft.LightSwitch.Framework.Base.DataWorkspace<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of a DataWorkspace.  Changes can be made to data sources in the new instance independent of changes made to data sources in the default DataWorkspace.
        /// </summary>
        public DataWorkspace() : base()
        {
        }
    
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Gets the NeuroPatData datasource.  This provides members to query and update data in the data source.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.NeuroPatDataService NeuroPatData
        {
            get
            {
                return global::LightSwitchApplication.DataWorkspace.DetailsClass.GetValue(this, global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.NeuroPatData);
            }
        }
        
        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.DataWorkspaceDetails<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySet>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.NeuroPatData;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.DataWorkspacePropertySet<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.NeuroPatDataService> NeuroPatData
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.NeuroPatData) as global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.NeuroPatDataService>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.NeuroPatDataService>.Entry
                    NeuroPatData = new global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.NeuroPatDataService>.Entry(
                        "NeuroPatData",
                        global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties._NeuroPatData_Stub);
                private static void _NeuroPatData_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DataWorkspace.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.NeuroPatDataService>.Data> c, global::LightSwitchApplication.DataWorkspace.DetailsClass d, object sf)
                {
                    c(d, ref d._NeuroPatData, sf);
                }
                 
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.NeuroPatDataService>.Data _NeuroPatData;
            
        }
    
        #endregion
    }
    
    #endregion
    
    #region Data Services
    
    /// <summary>
    /// Provides members to query and update data in the NeuroPatData datasource.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class NeuroPatData : global::Microsoft.LightSwitch.Framework.Base.DataService<global::LightSwitchApplication.NeuroPatData, global::LightSwitchApplication.NeuroPatData.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// This constructor is used for the internal LightSwitch framework. Use DataWorkspace instead.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public NeuroPatData() : base()
        {
        }
    
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Gets the Patient_Mains entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Patient_Main> Patient_Mains
        {
            get
            {
                return global::LightSwitchApplication.NeuroPatData.DetailsClass.GetValue(this, global::LightSwitchApplication.NeuroPatData.DetailsClass.PropertySetProperties.Patient_Mains);
            }
        }
        
        #endregion
    
        #region Queries
    
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="Discharged">
        /// The value of the 'Discharged' key property of the entity to retrieve.
        /// </param>
        /// <param name="Complication">
        /// The value of the 'Complication' key property of the entity to retrieve.
        /// </param>
        /// <param name="M___M">
        /// The value of the 'M___M' key property of the entity to retrieve.
        /// </param>
        /// <param name="TBI">
        /// The value of the 'TBI' key property of the entity to retrieve.
        /// </param>
        /// <param name="TBI_f_u_complete">
        /// The value of the 'TBI_f_u_complete' key property of the entity to retrieve.
        /// </param>
        /// <param name="Preferred_1">
        /// The value of the 'Preferred_1' key property of the entity to retrieve.
        /// </param>
        /// <param name="Preferred_2">
        /// The value of the 'Preferred_2' key property of the entity to retrieve.
        /// </param>
        /// <param name="Preferred_3">
        /// The value of the 'Preferred_3' key property of the entity to retrieve.
        /// </param>
        /// <param name="PCP_f_u_done">
        /// The value of the 'PCP_f_u_done' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Patient_Main Patient_Mains_Single(global::System.Nullable<bool> Discharged, global::System.Nullable<bool> Complication, global::System.Nullable<bool> M___M, global::System.Nullable<bool> TBI, global::System.Nullable<bool> TBI_f_u_complete, global::System.Nullable<bool> Preferred_1, global::System.Nullable<bool> Preferred_2, global::System.Nullable<bool> Preferred_3, global::System.Nullable<bool> PCP_f_u_done)
        {
            return this.Details.Methods.Patient_Mains_Single.CreateInvocation(Discharged, Complication, M___M, TBI, TBI_f_u_complete, Preferred_1, Preferred_2, Preferred_3, PCP_f_u_done).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="Discharged">
        /// The value of the 'Discharged' key property of the entity to retrieve.
        /// </param>
        /// <param name="Complication">
        /// The value of the 'Complication' key property of the entity to retrieve.
        /// </param>
        /// <param name="M___M">
        /// The value of the 'M___M' key property of the entity to retrieve.
        /// </param>
        /// <param name="TBI">
        /// The value of the 'TBI' key property of the entity to retrieve.
        /// </param>
        /// <param name="TBI_f_u_complete">
        /// The value of the 'TBI_f_u_complete' key property of the entity to retrieve.
        /// </param>
        /// <param name="Preferred_1">
        /// The value of the 'Preferred_1' key property of the entity to retrieve.
        /// </param>
        /// <param name="Preferred_2">
        /// The value of the 'Preferred_2' key property of the entity to retrieve.
        /// </param>
        /// <param name="Preferred_3">
        /// The value of the 'Preferred_3' key property of the entity to retrieve.
        /// </param>
        /// <param name="PCP_f_u_done">
        /// The value of the 'PCP_f_u_done' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Patient_Main Patient_Mains_SingleOrDefault(global::System.Nullable<bool> Discharged, global::System.Nullable<bool> Complication, global::System.Nullable<bool> M___M, global::System.Nullable<bool> TBI, global::System.Nullable<bool> TBI_f_u_complete, global::System.Nullable<bool> Preferred_1, global::System.Nullable<bool> Preferred_2, global::System.Nullable<bool> Preferred_3, global::System.Nullable<bool> PCP_f_u_done)
        {
            return this.Details.Methods.Patient_Mains_SingleOrDefault.CreateInvocation(Discharged, Complication, M___M, TBI, TBI_f_u_complete, Preferred_1, Preferred_2, Preferred_3, PCP_f_u_done).Execute();
        }
        
        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.DataServiceDetails<global::LightSwitchApplication.NeuroPatData, global::LightSwitchApplication.NeuroPatData.DetailsClass, global::LightSwitchApplication.NeuroPatData.DetailsClass.PropertySet, global::LightSwitchApplication.NeuroPatData.DetailsClass.MethodSet>
        {
    
            static DetailsClass()
            {
                var initializeMethodEntry = global::LightSwitchApplication.NeuroPatData.DetailsClass.MethodSetProperties.Patient_Mains_Single;
                var initializePropertyEntry = global::LightSwitchApplication.NeuroPatData.DetailsClass.PropertySetProperties.Patient_Mains;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::LightSwitchApplication.NeuroPatData.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.NeuroPatData.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet : global::Microsoft.LightSwitch.Details.Framework.Base.DataServiceMethodSet<global::LightSwitchApplication.NeuroPatData, global::LightSwitchApplication.NeuroPatData.DetailsClass>
            {
    
                public MethodSet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NeuroPatData, global::LightSwitchApplication.NeuroPatData.DetailsClass, global::LightSwitchApplication.Patient_Main> Patient_Mains_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.NeuroPatData.DetailsClass.MethodSetProperties.Patient_Mains_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NeuroPatData, global::LightSwitchApplication.NeuroPatData.DetailsClass, global::LightSwitchApplication.Patient_Main>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NeuroPatData, global::LightSwitchApplication.NeuroPatData.DetailsClass, global::LightSwitchApplication.Patient_Main> Patient_Mains_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.NeuroPatData.DetailsClass.MethodSetProperties.Patient_Mains_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NeuroPatData, global::LightSwitchApplication.NeuroPatData.DetailsClass, global::LightSwitchApplication.Patient_Main>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.DataServicePropertySet<global::LightSwitchApplication.NeuroPatData, global::LightSwitchApplication.NeuroPatData.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.NeuroPatData, global::LightSwitchApplication.NeuroPatData.DetailsClass, global::LightSwitchApplication.Patient_Main> Patient_Mains
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.NeuroPatData.DetailsClass.PropertySetProperties.Patient_Mains) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.NeuroPatData, global::LightSwitchApplication.NeuroPatData.DetailsClass, global::LightSwitchApplication.Patient_Main>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class MethodSetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NeuroPatData, global::LightSwitchApplication.NeuroPatData.DetailsClass, global::LightSwitchApplication.Patient_Main>.Entry
                    Patient_Mains_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NeuroPatData, global::LightSwitchApplication.NeuroPatData.DetailsClass, global::LightSwitchApplication.Patient_Main>.Entry(
                        "Patient_Mains_Single",
                        global::LightSwitchApplication.NeuroPatData.DetailsClass.MethodSetProperties._Patient_Mains_Single_Stub);
                private static void _Patient_Mains_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.NeuroPatData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NeuroPatData, global::LightSwitchApplication.NeuroPatData.DetailsClass, global::LightSwitchApplication.Patient_Main>.Data> c, global::LightSwitchApplication.NeuroPatData.DetailsClass d, object sf)
                {
                    c(d, ref d._Patient_Mains_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NeuroPatData, global::LightSwitchApplication.NeuroPatData.DetailsClass, global::LightSwitchApplication.Patient_Main>.Entry
                    Patient_Mains_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NeuroPatData, global::LightSwitchApplication.NeuroPatData.DetailsClass, global::LightSwitchApplication.Patient_Main>.Entry(
                        "Patient_Mains_SingleOrDefault",
                        global::LightSwitchApplication.NeuroPatData.DetailsClass.MethodSetProperties._Patient_Mains_SingleOrDefault_Stub);
                private static void _Patient_Mains_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.NeuroPatData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NeuroPatData, global::LightSwitchApplication.NeuroPatData.DetailsClass, global::LightSwitchApplication.Patient_Main>.Data> c, global::LightSwitchApplication.NeuroPatData.DetailsClass d, object sf)
                {
                    c(d, ref d._Patient_Mains_SingleOrDefault, sf);
                }
    
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.NeuroPatData, global::LightSwitchApplication.NeuroPatData.DetailsClass, global::LightSwitchApplication.Patient_Main>.Entry
                    Patient_Mains = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.NeuroPatData, global::LightSwitchApplication.NeuroPatData.DetailsClass, global::LightSwitchApplication.Patient_Main>.Entry(
                        "Patient_Mains",
                        global::LightSwitchApplication.NeuroPatData.DetailsClass.PropertySetProperties._Patient_Mains_Stub);
                private static void _Patient_Mains_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.NeuroPatData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.NeuroPatData, global::LightSwitchApplication.NeuroPatData.DetailsClass, global::LightSwitchApplication.Patient_Main>.Data> c, global::LightSwitchApplication.NeuroPatData.DetailsClass d, object sf)
                {
                    c(d, ref d._Patient_Mains, sf);
                }
     
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.NeuroPatData, global::LightSwitchApplication.NeuroPatData.DetailsClass, global::LightSwitchApplication.Patient_Main>.Data _Patient_Mains;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NeuroPatData, global::LightSwitchApplication.NeuroPatData.DetailsClass, global::LightSwitchApplication.Patient_Main>.Data _Patient_Mains_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.NeuroPatData, global::LightSwitchApplication.NeuroPatData.DetailsClass, global::LightSwitchApplication.Patient_Main>.Data _Patient_Mains_SingleOrDefault;
            
        }
    
        #endregion
    }
    
    #endregion
    
}
