//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace LightSwitchApplication.Implementation
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class NeuroPatData : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new NeuroPatData object using the connection string found in the 'NeuroPatData' section of the application configuration file.
        /// </summary>
        public NeuroPatData() : base("name=NeuroPatData", "NeuroPatData")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NeuroPatData object.
        /// </summary>
        public NeuroPatData(string connectionString) : base(connectionString, "NeuroPatData")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NeuroPatData object.
        /// </summary>
        public NeuroPatData(EntityConnection connection) : base(connection, "NeuroPatData")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Patient_Main> Patient_Mains
        {
            get
            {
                if ((_Patient_Mains == null))
                {
                    _Patient_Mains = base.CreateObjectSet<Patient_Main>("Patient_Mains");
                }
                return _Patient_Mains;
            }
        }
        private ObjectSet<Patient_Main> _Patient_Mains;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Patient_Mains EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPatient_Mains(Patient_Main patient_Main)
        {
            base.AddObject("Patient_Mains", patient_Main);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="Patient_Main")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Patient_Main : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Patient_Main object.
        /// </summary>
        /// <param name="discharged">Initial value of the Discharged property.</param>
        /// <param name="complication">Initial value of the Complication property.</param>
        /// <param name="m___M">Initial value of the M___M property.</param>
        /// <param name="tBI">Initial value of the TBI property.</param>
        /// <param name="tBI_f_u_complete">Initial value of the TBI_f_u_complete property.</param>
        /// <param name="preferred_1">Initial value of the Preferred_1 property.</param>
        /// <param name="preferred_2">Initial value of the Preferred_2 property.</param>
        /// <param name="preferred_3">Initial value of the Preferred_3 property.</param>
        /// <param name="pCP_f_u_done">Initial value of the PCP_f_u_done property.</param>
        public static Patient_Main CreatePatient_Main(global::System.Boolean discharged, global::System.Boolean complication, global::System.Boolean m___M, global::System.Boolean tBI, global::System.Boolean tBI_f_u_complete, global::System.Boolean preferred_1, global::System.Boolean preferred_2, global::System.Boolean preferred_3, global::System.Boolean pCP_f_u_done)
        {
            Patient_Main patient_Main = new Patient_Main();
            patient_Main.Discharged = discharged;
            patient_Main.Complication = complication;
            patient_Main.M___M = m___M;
            patient_Main.TBI = tBI;
            patient_Main.TBI_f_u_complete = tBI_f_u_complete;
            patient_Main.Preferred_1 = preferred_1;
            patient_Main.Preferred_2 = preferred_2;
            patient_Main.Preferred_3 = preferred_3;
            patient_Main.PCP_f_u_done = pCP_f_u_done;
            return patient_Main;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ID1
        {
            get
            {
                return _ID1;
            }
            set
            {
                OnID1Changing(value);
                ReportPropertyChanging("ID1");
                _ID1 = value;
                ReportPropertyChanged("ID1");
                OnID1Changed();
            }
        }
        private Nullable<global::System.Int32> _ID1;
        partial void OnID1Changing(Nullable<global::System.Int32> value);
        partial void OnID1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Last_Name
        {
            get
            {
                return _Last_Name;
            }
            set
            {
                OnLast_NameChanging(value);
                ReportPropertyChanging("Last_Name");
                _Last_Name = value;
                ReportPropertyChanged("Last_Name");
                OnLast_NameChanged();
            }
        }
        private global::System.String _Last_Name;
        partial void OnLast_NameChanging(global::System.String value);
        partial void OnLast_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String First_Name
        {
            get
            {
                return _First_Name;
            }
            set
            {
                OnFirst_NameChanging(value);
                ReportPropertyChanging("First_Name");
                _First_Name = value;
                ReportPropertyChanged("First_Name");
                OnFirst_NameChanged();
            }
        }
        private global::System.String _First_Name;
        partial void OnFirst_NameChanging(global::System.String value);
        partial void OnFirst_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MR
        {
            get
            {
                return _MR;
            }
            set
            {
                OnMRChanging(value);
                ReportPropertyChanging("MR");
                _MR = value;
                ReportPropertyChanged("MR");
                OnMRChanged();
            }
        }
        private global::System.String _MR;
        partial void OnMRChanging(global::System.String value);
        partial void OnMRChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Age
        {
            get
            {
                return _Age;
            }
            set
            {
                OnAgeChanging(value);
                ReportPropertyChanging("Age");
                _Age = value;
                ReportPropertyChanged("Age");
                OnAgeChanged();
            }
        }
        private global::System.String _Age;
        partial void OnAgeChanging(global::System.String value);
        partial void OnAgeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Admit_Date
        {
            get
            {
                return _Admit_Date;
            }
            set
            {
                OnAdmit_DateChanging(value);
                ReportPropertyChanging("Admit_Date");
                _Admit_Date = value;
                ReportPropertyChanged("Admit_Date");
                OnAdmit_DateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Admit_Date;
        partial void OnAdmit_DateChanging(Nullable<global::System.DateTime> value);
        partial void OnAdmit_DateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Floor
        {
            get
            {
                return _Floor;
            }
            set
            {
                OnFloorChanging(value);
                ReportPropertyChanging("Floor");
                _Floor = value;
                ReportPropertyChanged("Floor");
                OnFloorChanged();
            }
        }
        private global::System.String _Floor;
        partial void OnFloorChanging(global::System.String value);
        partial void OnFloorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Bed
        {
            get
            {
                return _Bed;
            }
            set
            {
                OnBedChanging(value);
                ReportPropertyChanging("Bed");
                _Bed = value;
                ReportPropertyChanged("Bed");
                OnBedChanged();
            }
        }
        private Nullable<global::System.Int32> _Bed;
        partial void OnBedChanging(Nullable<global::System.Int32> value);
        partial void OnBedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Staff
        {
            get
            {
                return _Staff;
            }
            set
            {
                OnStaffChanging(value);
                ReportPropertyChanging("Staff");
                _Staff = value;
                ReportPropertyChanged("Staff");
                OnStaffChanged();
            }
        }
        private global::System.String _Staff;
        partial void OnStaffChanging(global::System.String value);
        partial void OnStaffChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Op_Res
        {
            get
            {
                return _Op_Res;
            }
            set
            {
                OnOp_ResChanging(value);
                ReportPropertyChanging("Op_Res");
                _Op_Res = value;
                ReportPropertyChanged("Op_Res");
                OnOp_ResChanged();
            }
        }
        private global::System.String _Op_Res;
        partial void OnOp_ResChanging(global::System.String value);
        partial void OnOp_ResChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Op_Res_2
        {
            get
            {
                return _Op_Res_2;
            }
            set
            {
                OnOp_Res_2Changing(value);
                ReportPropertyChanging("Op_Res_2");
                _Op_Res_2 = value;
                ReportPropertyChanged("Op_Res_2");
                OnOp_Res_2Changed();
            }
        }
        private global::System.String _Op_Res_2;
        partial void OnOp_Res_2Changing(global::System.String value);
        partial void OnOp_Res_2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Consult_Inpatient
        {
            get
            {
                return _Consult_Inpatient;
            }
            set
            {
                OnConsult_InpatientChanging(value);
                ReportPropertyChanging("Consult_Inpatient");
                _Consult_Inpatient = value;
                ReportPropertyChanged("Consult_Inpatient");
                OnConsult_InpatientChanged();
            }
        }
        private global::System.String _Consult_Inpatient;
        partial void OnConsult_InpatientChanging(global::System.String value);
        partial void OnConsult_InpatientChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Diagnosis
        {
            get
            {
                return _Diagnosis;
            }
            set
            {
                OnDiagnosisChanging(value);
                ReportPropertyChanging("Diagnosis");
                _Diagnosis = value;
                ReportPropertyChanged("Diagnosis");
                OnDiagnosisChanged();
            }
        }
        private global::System.String _Diagnosis;
        partial void OnDiagnosisChanging(global::System.String value);
        partial void OnDiagnosisChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Procedures
        {
            get
            {
                return _Procedures;
            }
            set
            {
                OnProceduresChanging(value);
                ReportPropertyChanging("Procedures");
                _Procedures = value;
                ReportPropertyChanged("Procedures");
                OnProceduresChanged();
            }
        }
        private global::System.String _Procedures;
        partial void OnProceduresChanging(global::System.String value);
        partial void OnProceduresChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Note
        {
            get
            {
                return _Note;
            }
            set
            {
                OnNoteChanging(value);
                ReportPropertyChanging("Note");
                _Note = value;
                ReportPropertyChanged("Note");
                OnNoteChanged();
            }
        }
        private global::System.String _Note;
        partial void OnNoteChanging(global::System.String value);
        partial void OnNoteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Discharged
        {
            get
            {
                return _Discharged;
            }
            set
            {
                if (_Discharged != value)
                {
                    OnDischargedChanging(value);
                    ReportPropertyChanging("Discharged");
                    _Discharged = value;
                    ReportPropertyChanged("Discharged");
                    OnDischargedChanged();
                }
            }
        }
        private global::System.Boolean _Discharged;
        partial void OnDischargedChanging(global::System.Boolean value);
        partial void OnDischargedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Discharge_Date
        {
            get
            {
                return _Discharge_Date;
            }
            set
            {
                OnDischarge_DateChanging(value);
                ReportPropertyChanging("Discharge_Date");
                _Discharge_Date = value;
                ReportPropertyChanged("Discharge_Date");
                OnDischarge_DateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Discharge_Date;
        partial void OnDischarge_DateChanging(Nullable<global::System.DateTime> value);
        partial void OnDischarge_DateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Complication
        {
            get
            {
                return _Complication;
            }
            set
            {
                if (_Complication != value)
                {
                    OnComplicationChanging(value);
                    ReportPropertyChanging("Complication");
                    _Complication = value;
                    ReportPropertyChanged("Complication");
                    OnComplicationChanged();
                }
            }
        }
        private global::System.Boolean _Complication;
        partial void OnComplicationChanging(global::System.Boolean value);
        partial void OnComplicationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Complication__1
        {
            get
            {
                return _Complication__1;
            }
            set
            {
                OnComplication__1Changing(value);
                ReportPropertyChanging("Complication__1");
                _Complication__1 = value;
                ReportPropertyChanged("Complication__1");
                OnComplication__1Changed();
            }
        }
        private global::System.String _Complication__1;
        partial void OnComplication__1Changing(global::System.String value);
        partial void OnComplication__1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Complication__2
        {
            get
            {
                return _Complication__2;
            }
            set
            {
                OnComplication__2Changing(value);
                ReportPropertyChanging("Complication__2");
                _Complication__2 = value;
                ReportPropertyChanged("Complication__2");
                OnComplication__2Changed();
            }
        }
        private global::System.String _Complication__2;
        partial void OnComplication__2Changing(global::System.String value);
        partial void OnComplication__2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Complication_Description
        {
            get
            {
                return _Complication_Description;
            }
            set
            {
                OnComplication_DescriptionChanging(value);
                ReportPropertyChanging("Complication_Description");
                _Complication_Description = value;
                ReportPropertyChanged("Complication_Description");
                OnComplication_DescriptionChanged();
            }
        }
        private global::System.String _Complication_Description;
        partial void OnComplication_DescriptionChanging(global::System.String value);
        partial void OnComplication_DescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Research_Pt
        {
            get
            {
                return _Research_Pt;
            }
            set
            {
                OnResearch_PtChanging(value);
                ReportPropertyChanging("Research_Pt");
                _Research_Pt = value;
                ReportPropertyChanged("Research_Pt");
                OnResearch_PtChanged();
            }
        }
        private global::System.String _Research_Pt;
        partial void OnResearch_PtChanging(global::System.String value);
        partial void OnResearch_PtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean M___M
        {
            get
            {
                return _M___M;
            }
            set
            {
                if (_M___M != value)
                {
                    OnM___MChanging(value);
                    ReportPropertyChanging("M___M");
                    _M___M = value;
                    ReportPropertyChanged("M___M");
                    OnM___MChanged();
                }
            }
        }
        private global::System.Boolean _M___M;
        partial void OnM___MChanging(global::System.Boolean value);
        partial void OnM___MChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = value;
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> FT
        {
            get
            {
                return _FT;
            }
            set
            {
                OnFTChanging(value);
                ReportPropertyChanging("FT");
                _FT = value;
                ReportPropertyChanged("FT");
                OnFTChanged();
            }
        }
        private Nullable<global::System.Int32> _FT;
        partial void OnFTChanging(Nullable<global::System.Int32> value);
        partial void OnFTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean TBI
        {
            get
            {
                return _TBI;
            }
            set
            {
                if (_TBI != value)
                {
                    OnTBIChanging(value);
                    ReportPropertyChanging("TBI");
                    _TBI = value;
                    ReportPropertyChanged("TBI");
                    OnTBIChanged();
                }
            }
        }
        private global::System.Boolean _TBI;
        partial void OnTBIChanging(global::System.Boolean value);
        partial void OnTBIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean TBI_f_u_complete
        {
            get
            {
                return _TBI_f_u_complete;
            }
            set
            {
                if (_TBI_f_u_complete != value)
                {
                    OnTBI_f_u_completeChanging(value);
                    ReportPropertyChanging("TBI_f_u_complete");
                    _TBI_f_u_complete = value;
                    ReportPropertyChanged("TBI_f_u_complete");
                    OnTBI_f_u_completeChanged();
                }
            }
        }
        private global::System.Boolean _TBI_f_u_complete;
        partial void OnTBI_f_u_completeChanging(global::System.Boolean value);
        partial void OnTBI_f_u_completeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PCP
        {
            get
            {
                return _PCP;
            }
            set
            {
                OnPCPChanging(value);
                ReportPropertyChanging("PCP");
                _PCP = value;
                ReportPropertyChanged("PCP");
                OnPCPChanged();
            }
        }
        private global::System.String _PCP;
        partial void OnPCPChanging(global::System.String value);
        partial void OnPCPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address_line__1
        {
            get
            {
                return _Address_line__1;
            }
            set
            {
                OnAddress_line__1Changing(value);
                ReportPropertyChanging("Address_line__1");
                _Address_line__1 = value;
                ReportPropertyChanged("Address_line__1");
                OnAddress_line__1Changed();
            }
        }
        private global::System.String _Address_line__1;
        partial void OnAddress_line__1Changing(global::System.String value);
        partial void OnAddress_line__1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address_line__2
        {
            get
            {
                return _Address_line__2;
            }
            set
            {
                OnAddress_line__2Changing(value);
                ReportPropertyChanging("Address_line__2");
                _Address_line__2 = value;
                ReportPropertyChanged("Address_line__2");
                OnAddress_line__2Changed();
            }
        }
        private global::System.String _Address_line__2;
        partial void OnAddress_line__2Changing(global::System.String value);
        partial void OnAddress_line__2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address_line__3
        {
            get
            {
                return _Address_line__3;
            }
            set
            {
                OnAddress_line__3Changing(value);
                ReportPropertyChanging("Address_line__3");
                _Address_line__3 = value;
                ReportPropertyChanged("Address_line__3");
                OnAddress_line__3Changed();
            }
        }
        private global::System.String _Address_line__3;
        partial void OnAddress_line__3Changing(global::System.String value);
        partial void OnAddress_line__3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Preferred_1
        {
            get
            {
                return _Preferred_1;
            }
            set
            {
                if (_Preferred_1 != value)
                {
                    OnPreferred_1Changing(value);
                    ReportPropertyChanging("Preferred_1");
                    _Preferred_1 = value;
                    ReportPropertyChanged("Preferred_1");
                    OnPreferred_1Changed();
                }
            }
        }
        private global::System.Boolean _Preferred_1;
        partial void OnPreferred_1Changing(global::System.Boolean value);
        partial void OnPreferred_1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String E_mail
        {
            get
            {
                return _E_mail;
            }
            set
            {
                OnE_mailChanging(value);
                ReportPropertyChanging("E_mail");
                _E_mail = value;
                ReportPropertyChanged("E_mail");
                OnE_mailChanged();
            }
        }
        private global::System.String _E_mail;
        partial void OnE_mailChanging(global::System.String value);
        partial void OnE_mailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Preferred_2
        {
            get
            {
                return _Preferred_2;
            }
            set
            {
                if (_Preferred_2 != value)
                {
                    OnPreferred_2Changing(value);
                    ReportPropertyChanging("Preferred_2");
                    _Preferred_2 = value;
                    ReportPropertyChanged("Preferred_2");
                    OnPreferred_2Changed();
                }
            }
        }
        private global::System.Boolean _Preferred_2;
        partial void OnPreferred_2Changing(global::System.Boolean value);
        partial void OnPreferred_2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tel
        {
            get
            {
                return _Tel;
            }
            set
            {
                OnTelChanging(value);
                ReportPropertyChanging("Tel");
                _Tel = value;
                ReportPropertyChanged("Tel");
                OnTelChanged();
            }
        }
        private global::System.String _Tel;
        partial void OnTelChanging(global::System.String value);
        partial void OnTelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Preferred_3
        {
            get
            {
                return _Preferred_3;
            }
            set
            {
                if (_Preferred_3 != value)
                {
                    OnPreferred_3Changing(value);
                    ReportPropertyChanging("Preferred_3");
                    _Preferred_3 = value;
                    ReportPropertyChanged("Preferred_3");
                    OnPreferred_3Changed();
                }
            }
        }
        private global::System.Boolean _Preferred_3;
        partial void OnPreferred_3Changing(global::System.Boolean value);
        partial void OnPreferred_3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Referring_Phys
        {
            get
            {
                return _Referring_Phys;
            }
            set
            {
                OnReferring_PhysChanging(value);
                ReportPropertyChanging("Referring_Phys");
                _Referring_Phys = value;
                ReportPropertyChanged("Referring_Phys");
                OnReferring_PhysChanged();
            }
        }
        private global::System.String _Referring_Phys;
        partial void OnReferring_PhysChanging(global::System.String value);
        partial void OnReferring_PhysChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BC_notes
        {
            get
            {
                return _BC_notes;
            }
            set
            {
                OnBC_notesChanging(value);
                ReportPropertyChanging("BC_notes");
                _BC_notes = value;
                ReportPropertyChanged("BC_notes");
                OnBC_notesChanged();
            }
        }
        private global::System.String _BC_notes;
        partial void OnBC_notesChanging(global::System.String value);
        partial void OnBC_notesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String KJB_notes
        {
            get
            {
                return _KJB_notes;
            }
            set
            {
                OnKJB_notesChanging(value);
                ReportPropertyChanging("KJB_notes");
                _KJB_notes = value;
                ReportPropertyChanged("KJB_notes");
                OnKJB_notesChanged();
            }
        }
        private global::System.String _KJB_notes;
        partial void OnKJB_notesChanging(global::System.String value);
        partial void OnKJB_notesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean PCP_f_u_done
        {
            get
            {
                return _PCP_f_u_done;
            }
            set
            {
                if (_PCP_f_u_done != value)
                {
                    OnPCP_f_u_doneChanging(value);
                    ReportPropertyChanging("PCP_f_u_done");
                    _PCP_f_u_done = value;
                    ReportPropertyChanged("PCP_f_u_done");
                    OnPCP_f_u_doneChanged();
                }
            }
        }
        private global::System.Boolean _PCP_f_u_done;
        partial void OnPCP_f_u_doneChanging(global::System.Boolean value);
        partial void OnPCP_f_u_doneChanged();

        #endregion

    
    }

    #endregion

    
}
